Repository bedag/helm-charts, pull requests merged in 2021-02, with the labels that each got.

#33 [manifests]: Helm 3.5 Fixing
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/README.md.gotmpl
  charts/manifests/templates/Quickstart.md
  charts/manifests/templates/README.md
  charts/manifests/templates/manifests/README.md
  charts/manifests/templates/manifests/_bundle.tpl
  charts/manifests/templates/manifests/_cronjob.tpl
  charts/manifests/templates/manifests/_daemonset.tpl
  charts/manifests/templates/manifests/_deployment.tpl
  charts/manifests/templates/manifests/_horizontalPodAutoscaler.tpl
  charts/manifests/templates/manifests/_ingress.tpl
  charts/manifests/templates/manifests/_job.tpl
  charts/manifests/templates/manifests/_networkPolicy.tpl
  charts/manifests/templates/manifests/_persistentVolumeClaim.tpl
  charts/manifests/templates/manifests/_pod.tpl
  charts/manifests/templates/manifests/_podDisruptionBudget.tpl
  charts/manifests/templates/manifests/_service.tpl
  charts/manifests/templates/manifests/_serviceAccount.tpl
  charts/manifests/templates/manifests/_serviceMonitor.tpl
  charts/manifests/templates/manifests/_statefulset.tpl
  charts/manifests/templates/manifests/templates/_bundleExtras.tpl
  charts/manifests/templates/manifests/templates/_containerTpl.tpl
  charts/manifests/templates/manifests/templates/_jobTpl.tpl
  charts/manifests/templates/manifests/templates/_podTpl.tpl
  charts/manifests/templates/manifests/templates/_pvcTpl.tpl
  charts/manifests/templates/utils/_common.tpl
  charts/manifests/templates/utils/_intern.tpl
  charts/manifests/templates/values/manifests/_service.yaml
Labels: bug, enhancement

#34 [manifests] bugfix missing overwrites
  charts/manifests/Chart.yaml
  charts/manifests/README.md.gotmpl
  charts/manifests/templates/manifests/templates/_bundleExtras.tpl
Labels: bug, documentation

#39 [Housekeeping] Fix parameter for generating statefulset values for frontend
  charts/manifests/Chart.yaml
  charts/manifests/templates/Quickstart.md
Labels: documentation

#36 [housekeeping]: Update Testing Action
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  ct.yaml
Labels: enhancement

#35 [e2g]: Chart Publish
  charts/e2g/.helmignore
  charts/e2g/Chart.yaml
  charts/e2g/README.md.gotmpl
  charts/e2g/examples/simple.yaml
  charts/e2g/templates/bundle.yaml
  charts/e2g/templates/e2g.tpl
  charts/e2g/values.yaml
Labels: initialization

#40 [housekeeping]: Auto Push Documentation
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
  charts/e2g/Chart.yaml
  charts/e2g/README.md
  charts/manifests/README.md.gotmpl
Labels: documentation
