Repository bedag/helm-charts, pull requests merged in 2021-01, with the labels that each got.

#12 [manifests] Deployment fix
  .github/workflows/helm-test.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
  .gitignore
  .kube-linter.yaml
  CONTRIBUTING.md
  charts/manifests/README.md
  charts/manifests/plugin/generator.sh
  charts/manifests/plugin/values-generator/README.md
  charts/manifests/plugin/values-generator/templates/values-generator.yaml
  charts/manifests/plugin/values-generator/values.yaml
  charts/manifests/templates/README.md
  charts/manifests/templates/manifests/_bundle.tpl
  charts/manifests/templates/manifests/_deployment.tpl
  charts/manifests/templates/manifests/_statefulset.tpl
  charts/manifests/templates/manifests/templates/_bundleExtras.tpl
  charts/manifests/templates/values/manifests/_deployment.yaml
  charts/manifests/templates/values/manifests/_statefulset.yaml
Labels: bug, enhancement

#17 [manifests] #15 adding daemonset
  charts/manifests/Chart.yaml
  charts/manifests/templates/manifests/README.md
  charts/manifests/templates/manifests/_daemonset.tpl
  charts/manifests/templates/manifests/templates/_bundleExtras.tpl
  charts/manifests/templates/values/manifests/_daemonset.yaml
Labels: enhancement

#18 [housekeeping] Bugfixes & Documentation
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .gitignore
  CONTRIBUTING.md
  charts/manifests/.helmignore
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/README.md.gotmpl
  charts/manifests/plugin/README.md
  charts/manifests/plugin/generator.sh
  charts/manifests/plugin/plugin.yaml
  charts/manifests/plugin/values-generator/.helmignore
  charts/manifests/plugin/values-generator/Chart.yaml
  charts/manifests/plugin/values-generator/README.md
  charts/manifests/plugin/values-generator/templates/values-generator.yaml
  charts/manifests/plugin/values-generator/values.yaml
  charts/manifests/templates/Quickstart.md
  charts/manifests/templates/manifests/_bundle.tpl
  charts/manifests/templates/manifests/_ingress.tpl
  charts/manifests/templates/manifests/templates/_containerTpl.tpl
  charts/manifests/templates/utils/_intern.tpl
  charts/manifests/templates/values/README.md
  charts/manifests/templates/values/manifests/templates/_containerTpl.yaml
Labels: bug, documentation, enhancement

#19 [housekeeping] Contribution documentation & Licenses
  .github/workflows/release.yml
  CONTRIBUTING.md
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_bundle.tpl
  charts/manifests/templates/manifests/_cronjob.tpl
  charts/manifests/templates/manifests/_daemonset.tpl
  charts/manifests/templates/manifests/_deployment.tpl
  charts/manifests/templates/manifests/_horizontalPodAutoscaler.tpl
  charts/manifests/templates/manifests/_ingress.tpl
  charts/manifests/templates/manifests/_job.tpl
  charts/manifests/templates/manifests/_networkPolicy.tpl
  charts/manifests/templates/manifests/_persistentVolumeClaim.tpl
  charts/manifests/templates/manifests/_pod.tpl
  charts/manifests/templates/manifests/_podDisruptionBudget.tpl
  charts/manifests/templates/manifests/_service.tpl
  charts/manifests/templates/manifests/_serviceAccount.tpl
  charts/manifests/templates/manifests/_serviceMonitor.tpl
  charts/manifests/templates/manifests/_statefulset.tpl
  charts/manifests/templates/manifests/templates/_bundleExtras.tpl
  charts/manifests/templates/manifests/templates/_containerTpl.tpl
  charts/manifests/templates/manifests/templates/_jobTpl.tpl
  charts/manifests/templates/manifests/templates/_podTpl.tpl
  charts/manifests/templates/manifests/templates/_pvcTpl.tpl
  charts/manifests/templates/presets/components/_jmxexporter.tpl
  charts/manifests/templates/presets/containers/_permissions.tpl
  charts/manifests/templates/presets/containers/_readiness.tpl
  charts/manifests/templates/utils/_common.tpl
  charts/manifests/templates/utils/_environment.tpl
  charts/manifests/templates/utils/_helpers.tpl
  charts/manifests/templates/utils/_intern.tpl
  charts/manifests/templates/utils/_notes.tpl
  charts/manifests/templates/utils/_presets.tpl
  charts/manifests/templates/utils/_values.tpl
  ct.yaml
Labels: documentation, enhancement

#21 [manifests]: HPA requries metrics
  CONTRIBUTING.md
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_horizontalPodAutoscaler.tpl
Labels: bug

#22 [manifests]: Fixed Cronjob Bugs
  CONTRIBUTING.md
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_cronjob.tpl
Labels: bug, enhancement

#23 [manifests]: Fix BundleExtras & Contribution
  CONTRIBUTING.md
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/templates/_bundleExtras.tpl
Labels: bug

#24 [manifests]: Cronjob Quoting
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_cronjob.tpl
Labels: bug

#26 [manifests]: Fix Ingress behvaior
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_ingress.tpl
  charts/manifests/templates/values/manifests/_ingress.yaml
Labels: bug

#28 [manifests]: Deployment structure inheritance
  CONTRIBUTING.md
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/README.md.gotmpl
  charts/manifests/templates/Quickstart.md
  charts/manifests/templates/README.md
  charts/manifests/templates/manifests/README.md
  charts/manifests/templates/manifests/_deployment.tpl
  charts/manifests/templates/manifests/templates/_containerTpl.tpl
  charts/manifests/templates/presets/README.md
  charts/manifests/templates/utils/README.md
  charts/manifests/templates/utils/_environment.tpl
Labels: bug

#30 [manifests]: Fix Pod Kind
  CONTRIBUTING.md
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_pod.tpl
Labels: bug

#31 [manifests]: Add missing Pod Name
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_pod.tpl
Labels: bug

#29 [manifests]: fix: add newline indents
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/templates/manifests/_daemonset.tpl
  charts/manifests/templates/manifests/_networkPolicy.tpl
  charts/manifests/templates/manifests/_statefulset.tpl
  charts/manifests/templates/manifests/templates/_podTpl.tpl
  charts/manifests/templates/presets/components/_jmxexporter.tpl
Labels: bug
