Repository bedag/helm-charts, pull requests merged in 2022-12, with the labels that each got.

#64 [chore]: chart deprecations
  .github/workflows/lint-and-test.yml
  .kube-linter.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  charts/crowd/.kube-linter.yaml
  charts/crowd/Chart.yaml
  charts/crowd/README.md
  charts/crowd/README.md.gotmpl
  charts/e2g/Chart.yaml
  charts/e2g/README.md
  charts/goblackhole/.kube-linter.yaml
  charts/goblackhole/Chart.yaml
  charts/goblackhole/README.md
  charts/kafdrop/.kube-linter.yaml
  charts/kafdrop/Chart.yaml
  charts/kafdrop/README.md
  charts/kafdrop/README.md.gotmpl
  charts/manifests/Chart.yaml
  charts/manifests/README.md
  charts/manifests/README.md.gotmpl
  charts/raw/Chart.yaml
  charts/raw/README.md
  ct.yaml
  lintconf.yaml
Labels: size/L

#65 [ci]: fix workflows (release)
  .github/workflows/pr-label.yml
  .github/workflows/pr-validate.yml
  .github/workflows/release.yml
Labels: size/M

#62 [common]: add common chart
  charts/common/.helmignore
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/ci/values.test.yaml
  charts/common/templates/_binaryfiles.yaml
  charts/common/templates/_configfiles.yaml
  charts/common/templates/_configmap.yaml
  charts/common/templates/_container.yaml
  charts/common/templates/_cronjob.yaml
  charts/common/templates/_deployment.yaml
  charts/common/templates/_files.yaml
  charts/common/templates/_ingress-ingress.yaml
  charts/common/templates/_ingress-secret.yaml
  charts/common/templates/_job.yaml
  charts/common/templates/_jobspec.yaml
  charts/common/templates/_networkpolicy.yaml
  charts/common/templates/_pod.yaml
  charts/common/templates/_pvcs.yaml
  charts/common/templates/_secret.yaml
  charts/common/templates/_service.yaml
  charts/common/templates/_servicemonitor-headless-service.yaml
  charts/common/templates/_servicemonitor-secret.yaml
  charts/common/templates/_servicemonitor-servicemonitor.yaml
  charts/common/templates/_statefulset.yaml
  charts/common/templates/helpers/_chartref.tpl
  charts/common/templates/helpers/_fullname.tpl
  charts/common/templates/helpers/_labels.tpl
  charts/common/templates/helpers/_name.tpl
  charts/common/templates/helpers/_semver.tpl
  charts/common/templates/includes.yaml
  charts/common/values.schema.json
  charts/common/values.yaml
  charts/crowd/templates/_crowd.tpl
  charts/crowd/values.yaml
  charts/e2g/Chart.yaml
  charts/e2g/README.md
  charts/e2g/examples/simple.yaml
  charts/e2g/templates/bundle.yaml
  charts/e2g/templates/e2g.tpl
  charts/e2g/values.yaml
  charts/goblackhole/Chart.yaml
  charts/goblackhole/README.md
  charts/goblackhole/README.md.gotmpl
  charts/goblackhole/templates/NOTES.txt
  charts/goblackhole/values.yaml
  charts/goblackhole/values_production.yaml
  charts/manifests/templates/manifests/_statefulset.tpl
  charts/manifests/templates/utils/_configs.tpl
  charts/raw/Chart.yaml
  charts/raw/README.md
  charts/raw/README.md.gotmpl
  charts/raw/templates/_rendering.tpl
  charts/raw/templates/resources.yaml
  charts/raw/values.yaml
  scripts/helm-docs.sh
Labels: size/XXL

#66 [common]: retrigger Release
  charts/common/Chart.yaml
  charts/common/README.md
Labels: size/XS

#67 [common]: Housekeeping
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/ci/values.test.yaml
  charts/common/templates/helpers/_labels.tpl
  charts/common/values.schema.json
  charts/common/values.yaml
Labels: enhancement, size/M
