Repository bedag/helm-charts, pull requests merged in 2023-04, with the labels that each got.

#77 [common]: add egress and namespaceSelector in networkpolicy
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/README.md.gotmpl
  charts/common/ci/values.test.yaml
  charts/common/templates/_networkpolicy-sections.yaml
  charts/common/templates/_networkpolicy.yaml
  charts/common/values.schema.json
  charts/common/values.yaml
Labels: size/L

#79 fix: annotations and labels
  charts/vcluster/Chart.yaml
  charts/vcluster/README.md
  charts/vcluster/ci/lifecycle-values.yaml
  charts/vcluster/templates/components/autoscaler/deployment.yaml
  charts/vcluster/templates/components/autoscaler/servicemonitor.yaml
  charts/vcluster/templates/components/kubernetes/admin-deployment.yaml
  charts/vcluster/templates/components/kubernetes/apiserver-deployment.yaml
  charts/vcluster/templates/components/kubernetes/controller-manager-deployment.yaml
  charts/vcluster/templates/components/kubernetes/konnectivity-server-deployment.yaml
  charts/vcluster/templates/components/kubernetes/scheduler-deployment.yaml
  charts/vcluster/templates/components/machine-controller/deployment.yaml
  charts/vcluster/templates/components/operating-system-manager/deployment.yaml
  charts/vcluster/templates/lifecycle/cronjob.yaml
  charts/vcluster/templates/lifecycle/job.yaml
  charts/vcluster/values.yaml
Labels: size/L

#80 [common]: add emptyDir volumes
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/ci/values.test.yaml
  charts/common/templates/_pod.yaml
  charts/common/values.yaml
Labels: size/M

#83 fix: correct konnectivity certs
  charts/vcluster/Chart.yaml
  charts/vcluster/README.md
  charts/vcluster/ci/components-values.yaml
  charts/vcluster/ci/konnectivity-default-values.yaml
  charts/vcluster/manifests/kubernetes/konnectivity-agent.yaml
  charts/vcluster/templates/components/kubernetes/apiserver/certs.yaml
  charts/vcluster/templates/components/kubernetes/etcd/certs.yaml
  charts/vcluster/templates/components/kubernetes/konnectivity/certs.yaml
  charts/vcluster/templates/components/kubernetes/konnectivity/manifests.yaml
  charts/vcluster/templates/components/kubernetes/kubernetes-certs.yaml
  charts/vcluster/templates/expose/certificate.yaml
  charts/vcluster/templates/expose/issuer.yaml
  charts/vcluster/templates/lifecycle/cronjob.yaml
  charts/vcluster/templates/pkg/_components.tpl
Labels: size/L

#84 ]vcluster]: fix correct agent port
  charts/vcluster/Chart.yaml
  charts/vcluster/README.md
  charts/vcluster/manifests/kubernetes/konnectivity-agent.yaml
Labels: size/XS

#85 [vcluster]: add etcd snapshot cronjob
  charts/vcluster/Chart.yaml
  charts/vcluster/README.md
  charts/vcluster/README.md.gotmpl
  charts/vcluster/templates/components/gitops/manifests.yaml
  charts/vcluster/templates/components/kubernetes/etcd/backup-job.yaml
  charts/vcluster/templates/components/kubernetes/etcd/backup-pvc.yaml
  charts/vcluster/templates/components/kubernetes/etcd/certs.yaml
  charts/vcluster/templates/components/kubernetes/etcd/service.yaml
  charts/vcluster/templates/components/kubernetes/etcd/statefulset.yaml
  charts/vcluster/templates/lifecycle/setup.yaml
  charts/vcluster/values.yaml
Labels: size/XL

#86 Feat/vcluster etcd backup
  charts/vcluster/Chart.yaml
  charts/vcluster/templates/components/kubernetes/_templates.tpl
  charts/vcluster/templates/components/kubernetes/admin/configmap.yaml
  charts/vcluster/templates/components/kubernetes/apiserver/deployment.yaml
  charts/vcluster/templates/pkg/_common.tpl
  charts/vcluster/values.yaml
Labels: size/S

#87 [vcluster]: fix argocd kubeconfig
  charts/vcluster/Chart.yaml
  charts/vcluster/README.md
  charts/vcluster/addons/scripts/configure-current.sh
  charts/vcluster/ci/kubeconfig-values.yaml
  charts/vcluster/ci/lifecycle-values.yaml
  charts/vcluster/templates/components/kubernetes/etcd/statefulset.yaml
  charts/vcluster/templates/lifecycle/cronjob.yaml
  charts/vcluster/templates/lifecycle/rbac.yaml
  charts/vcluster/values.yaml
Labels: size/L

#88 [vcluster]: fix argocd kubeconfig
  charts/vcluster/Chart.yaml
  charts/vcluster/README.md
  charts/vcluster/addons/scripts/configure-current.sh
Labels: size/S
