Repository bedag/helm-charts, pull requests merged in 2023-10, with the labels that each got.

#118 [common]: Make pullSecret configurable
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/templates/_pod.yaml
  charts/common/values.schema.json
  charts/common/values.yaml
Labels: size/M

#119 [common] includes as values
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/ci/values.test.yaml
  charts/common/templates/includes.yaml
  charts/common/values.schema.json
  charts/common/values.yaml
Labels: size/L

#121 [common]: add volume type csi
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/templates/_pod.yaml
  charts/common/values.yaml
Labels: size/S

#122 [common]: fix rendering of csi volume
  charts/common/Chart.yaml
  charts/common/README.md
  charts/common/ci/values.test.yaml
  charts/common/templates/_pod.yaml
Labels: size/S

#120 [vcluster]: Removing variable 'KUBERNETES_SERVICE_HOST' from no_proxy
  charts/vcluster/Chart.yaml
  charts/vcluster/README.md
  charts/vcluster/templates/pkg/_common.tpl
Labels: size/XS
